[global]
auto_run_game_delay = 0.1
last_selected_game = "Call of Duty World at War"
usernames = ["Mythical"]
last_selected_username = "Mythical"
global_args = []
auto_run_game = false
use_staging = false
theme = "tokyo-night"

[games."Call of Duty World at War"]
last_selected_game_mode = "Single Player"
game_directory = ""
game_args = []

[games."Nazi Zombies: Portable"]
game_directory = "Z:\\GitHub\\shoal\\src\\shoal\\assets\\nazi_zombies_portable"
last_selected_game_mode = "Single Player"
game_args = []
